app:
  port: 8080
  profiler_addr: "0.0.0.0:8099"
  check_connections_interval: 10m
  error_buffer: 100
  log:
    level: "info"

connections:
  postgres:
    addr: "db_postgresql:5432"
    database: "goservice"
    username: "postgres"
    password: "postgres"
    debug: false
  clickhouse:
    addr: "db_clickhouse:9000"
    database: "goservice"
    debug: false
  elasticsearch:
    addr: "http://db_elasticsearch:9200"
    database: "goservice"
    healthcheck_interval: "5s"
  redis:
    addr: "db_redis:6379"
    db: 0
    ttl: "12h"
  rabbitmq:
    server:
      qos: 5000
      server: "amqp://goservice:goservice@queue_rabbitmq:5672/"
      routing_key: "rk.test.income"
      queue:
        name: "test.income"
        durable: true
      exchange:
        name: "test"
        type: "direct"
        durable: true
    consumers:
      test_income:
        queue_name: "test.income"
        routing_key: "rk.test.income"
    publishers:
      test_outcome:
        exchange_name: "test.outcome"
        routing_key: "rk.test_outcome"
